const pages = [
  "home",
  "jobs for electrician",
  "jobs for plumber",
  "jobs for mechanic",
  "jobs for cook",
  "jobs for peon",
  "jobs for driver",
  "jobs for drivers",
  "jobs for housekeeping",
  "jobs for site workers",
  "jobs for securityguard",
  "jobs for security guard",
  "job for electrician",
  "job for plumber",
  "job for mechanic",
  "job for cook",
  "job for peon",
  "job for driver",
  "job for drivers",
  "job for housekeeping",
  "job for siteworkers",
  "job for securityguard",
  "job for security guard",
  "electrician",
  "plumber",
  "mechanic",
  "cook",
  "peon",
  "driver",
  "drivers",
  "housekeeping",
  "siteworkers",
  "site workers",
  "securityguard",
  "security guard",
  "electrician jobs",
  "plumber jobs",
  "mechanic jobs",
  "cook jobs",
  "peon jobs",
  "driver jobs",
  "drivers jobs",
  "housekeeping jobs",
  "siteworkers jobs",
  "securityguard jobs",
  "security guard jobs",
  "electrician ki job chahiye",
  "plumber ki job chahiye",
  "mechanic ki job chahiye",
  "cook ki job chahiye",
  "peon ki job chahiye",
  "driver ki job chahiye",
  "drivers ki job chahiye",
  "housekeeping ki job chahiye",
  "siteworkers ki job chahiye",
  "securityguard ki job chahiye",
  "security guard ki job chahiye",
  "electrician ki job chahie",
  "plumber ki job chahie",
  "mechanic ki job chahie",
  "cook ki job chahie",
  "peon ki job chahie",
  "driver ki job chahie",
  "drivers ki job chahie",
  "housekeeping ki job chahie",
  "siteworkers ki job chahie",
  "securityguard ki job chahie",
  "security guard ki job chahie",
  "electrician job",
  "plumber job",
  "mechanic job",
  "cook job",
  "peon job",
  "driver job",
  "drivers job",
  "housekeeping job",
  "siteworkers job",
  "securityguard job",
  "security guard job",
  "candidates for electrician",
  "candidates for plumber",
  "candidates for mechanic",
  "candidates for cook",
  "candidates for peon",
  "candidates for driver",
  "candidates for drivers",
  "candidates for housekeeping",
  "candidates for siteworkers",
  "candidates for securityguard",
  "candidates for security guard",
  "candidate for electrician",
  "candidate for plumber",
  "candidate for mechanic",
  "candidate for mechanics",
  "candidate for cook",
  "candidate for peon",
  "candidate for driver",
  "candidate for drivers",
  "candidate for housekeeping",
  "candidate for site workers",
  "candidate for securityguard",
  "candidate for security guard",
  "electrician candidate",
  "plumber candidate",
  "mechanic candidate",
  "cooking candidate",
  "peon candidate",
  "driver candidate",
  "drivers candidate",
  "housekeeping candidate",
  "siteworker candidate",
  "site worker candidate",
  "securityguard candidate",
  "security guard candidate",
  "electrician candidates",
  "plumber candidates",
  "mechanic candidates",
  "cooking candidates",
  "peon candidates",
  "driver candidates",
  "drivers candidates",
  "housekeeping candidates",
  "siteworker candidates",
  "site worker candidates",
  "securityguard candidates",
  "security guard candidates",
  "electrician chahie",
  "plumber chahie",
  "mechanic chahie",
  "cook chahie",
  "peon chahie",
  "driver chahie",
  "drivers chahie",
  "housekeeper chahie",
  "siteworker chahie",
  "securityguard chahie",
  "security guard chahie",
  "electrician chahiye",
  "plumber chahiye",
  "mechanic chahiye",
  "cook chahiye",
  "peon chahiye",
  "driver chahiye",
  "drivers chahiye",
  "housekeeper chahiye",
  "siteworker chahiye",
  "securityguard chahiye",
  "security guard chahiye",
  "post jobs",
  "post job",
  "registration",
  "register"
];
export default pages;